source 'https://gitee.com/zhenlove/zhenSpecs.git'
source 'https://cdn.cocoapods.org/'
use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'KMOnlineWeb_Example' do
  pod 'KMOnlineWeb', :path => '../'
  pod 'CocoaAsyncSocket','7.6.3', :modular_headers => true, :configurations => ['Debug']
  pod 'Bagel','1.3.2', :configurations => ['Debug']
end
