#use_frameworks!

platform :ios, '9.0'

target 'KMOnlineWeb_Example' do
  pod 'KMOnlineWeb', :path => '../'
  pod 'KMNetwork','0.1.2'
  pod 'CocoaAsyncSocket','7.6.3', :modular_headers => true, :configurations => ['Debug']
  pod 'Bagel','1.3.2', :configurations => ['Debug']
  target 'KMOnlineWeb_Tests' do
    inherit! :search_paths

    
  end
end
